### ISSUE TITLE
Additional X11 packages

### ISSUE THREAD

**Issue by epruesse** [conda-forge/staged-recipes#2640]
I've created PRs for a few more X11 packages:

- [x] xorg-libxft #2592 (X font library)
- [x] xorg-printproto #2594 (X print protocols, header only)
- [x] xorg-xbitmaps #2604 (X shared bitmaps, header only)
- [x] xorg-makedepend #2606 (X build tool)
- [x] xorg-libxp #2607 (X print library, needs xorg-xprintproto)
- [x] openmotif #2582 (GUI toolkit, needs xorg-libxft, xorg-xprintproto and xorg-xbitmaps)

@conda-forge/core The tests passed, except where the dependencies aren't (yet) met. Is there something I need to do so you can merge the PRs?

I've templated off of @pkgw's xorg packages, to make maintenance easier down the line.

**Comment by epruesse** [comment]
@pkgw Would you prefer to be listed as package maintainer in the xorg-* packages?

**Comment by pkgw** [comment]
Sure, thanks.

**Comment by epruesse** [comment]
@conda-forge/core The next three xorg packages (printproto #2594, xbitmaps #2604 and makedepend #2606) are ready and would love to be merged :)

(There is a point to the extra xorg packages. I'm having to resolve a longer dependency chain from the bottom up...)

**Comment by jakirkham** [comment]
It looks `openmotif` is the only one left (checked off the merged ones; hope that is ok). ( https://github.com/conda-forge/staged-recipes/pull/2582 ) Seems something needs to be fixed with CircleCI before it proceeds. Would you have time to look @epruesse?

**Comment by epruesse** [comment]
@jakirkham traveling abroad, sorry. Will try ASAP, but that may mean a few days.
